# Generated by Django 4.2.10 on 2024-04-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("visits", models.PositiveIntegerField()),
                ("likes", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ("index",),
            },
        ),
        migrations.CreateModel(
            name="EmpModel",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("company", models.CharField(max_length=30)),
                ("salary", models.PositiveIntegerField()),
                ("street", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("category", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("views", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ("index",),
            },
        ),
    ]
